AllCops:
  Exclude:
    - db/**/*.rb
    - script/*
    - bin/*
    - heroku_import.thor

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

HasAndBelongsToMany:
  Enabled: false
  Include:
    - app/models/**/*.rb
